### ISSUE TITLE
Scoop command in Readme does not work

### ISSUE THREAD

**Issue by Faedelity** [Slashbunny/gog-galaxy-plugin-downloader#11]
I just attempted to use Scoop to install this using the command in the Readme, and received the error "Couldn't find manifest for 'gog-galaxy-plugin-downloader'."

I copied and pasted the command twice in order to confirm I wasn't adding any extra spaces or the like.

**Comment by Slashbunny** [comment]
I haven't used it personally, it was added as part of #2. Perhaps @JanPokorny could take a look?

**Comment by JanPokorny** [comment]
@NocturneBlock It is located in the `extras` bucket, I somehow forgot to add that to the description. The correct way is to first run `scoop bucket add extras` and then the install command will work.
