### ISSUE TITLE
2.1 No download and works very bad

### ISSUE THREAD

**Issue by RaptorPharaoh** [Slashbunny/gog-galaxy-plugin-downloader#12]
Hello, I use your plugin since the v0.4 and worked fine all time, but when I launch the v2.1 the first time all went very bad.

1.-The v2.1 can't download anything, for example I deleted steam plugin and it doesn't download it again.
2.-The v2.1 can rename the folders but was very difficult, for example it can rename Steam v1 to Steam ABCDEF, after that made a copy called Steam v1 and the program stop to work, it won't do anything else until that I manually delete the folder Steam v1, after that the program process 1 plug at time.
3.-The plugins Rockstar and Origin had a critical fail and don't worked anymore, I have to manually download it and put it manually, now work again.
4.-After the first execution of v2.1 older versions don't work in any way.
5.-Sometimes the program say something about permissions, but i launch it with admin privileges and the plug's folder has all privileges for all users, system, everyone.

Note: I tried to download it again, use the BAT, restart the PC, rename the exe and folder.

I appreciate so much your work and I understand is  a hard job and work in progress, I don't complaint about it, I'm only want to report this issues because your tool is awesome and very useful, I don't know if is just me or someone else have this problems. 

Thanks. Have a good day.

**Comment by Slashbunny** [comment]
Thanks for the report. I had another person mention permission issues. I did most of my testing on Linux and I think it's a Windows thing. That is probably why nothing is working. I will look into it.

**Comment by Slashbunny** [comment]
Hi @RaptorPharaoh , try the new release:

https://github.com/Slashbunny/gog-galaxy-plugin-downloader/releases

**Comment by RaptorPharaoh** [comment]
@Slashbunny Hi, thanks a lot, the new version works perfectly :D
