### ISSUE TITLE
Can't install via scoop

### ISSUE THREAD

**Issue by katsanva** [Slashbunny/gog-galaxy-plugin-downloader#14]
It seems wrong naming issue - it searches for `gog-plugins-downloader-stores.exe` but probably should for `gog-plugins-downloader.exe`

```powershell
PS C:\Users\thisi> scoop install gog-galaxy-plugin-downloader
>>
Installing 'gog-galaxy-plugin-downloader' (0.2.2) [64bit]
gog-plugins-downloader-v0.2.2.zip (6,0 MB) [==================================================================] 100%
Checking hash of gog-plugins-downloader-v0.2.2.zip ... ok.
Extracting gog-plugins-downloader-v0.2.2.zip ... done.
Linking ~\scoop\apps\gog-galaxy-plugin-downloader\current => ~\scoop\apps\gog-galaxy-plugin-downloader\0.2.2
Creating shim for 'gog-plugins-downloader-stores'.
Can't shim 'gog-plugins-downloader-stores.exe': File doesn't exist.```

**Comment by Slashbunny** [comment]
@JanPokorny will probably need to correct this in the scoop package, since it's unaffiliated with this project. I removed the 3 separate executables a while ago. 

I'm guessing this needs to change? https://github.com/lukesampson/scoop-extras/blob/master/bucket/gog-galaxy-plugin-downloader.json

**Comment by JanPokorny** [comment]
@Slashbunny Hi, I'm sorry but I'm without a computer for a few days, writing this from my phone.

However if you wish to make the fix yourself, it's pretty easy. Just make a PR to change the "bin" field in the json file you linked to the correct executables, and also the "notes" field to reflect updated usage. (Or just delete the "notes" field, a GitHub link is shown anyway.) You can probably manage to do all that from the GitHub web editor, it's just pain to use on phone.

**Comment by Slashbunny** [comment]
It looks like this was reported in the scoop-extras project and fixed in https://github.com/lukesampson/scoop-extras/issues/3420
