### ISSUE TITLE
Fanatical plugin not updating

### ISSUE THREAD

**Issue by MagikGimp** [Slashbunny/gog-galaxy-plugin-downloader#19]
[https://github.com/nosyn00b/GOG2_Fanatical_Plugin](https://github.com/nosyn00b/GOG2_Fanatical_Plugin)

v0.0.2 was released a couple of days ago. I assumed this plugin was able to detect new releases automatically?

**Comment by Slashbunny** [comment]
See #18 - The [manifest.json](https://github.com/nosyn00b/GOG2_Fanatical_Plugin/blob/v0.0.2/src/manifest.json) was not updated. It still shows the version as `0.0.1`. The author will need to update that file to reflect the new version. GOG Galaxy and this tool both look at the `manifest.json` file to determine the version number.

**Comment by Slashbunny** [comment]
@MagikGimp - I am going to close this issue. I can't correct this until `manifest.json` is updated with the correct version number in the Fanatical plugin's repository (it still shows `0.0.1`). Thanks!
