### ISSUE TITLE
gray screen when rockstar login has been filled in

### ISSUE THREAD

**Issue by Tjoeser** [Slashbunny/gog-galaxy-plugin-downloader#24]
![image](https://user-images.githubusercontent.com/86958571/188850048-d365d946-9ab6-46da-8cc8-9f38b1a05ffa.png)

**Comment by Slashbunny** [comment]
This is just a download tool, any issues with the integrations themselves should be opened in the integration's Github page. This problem sounds similar to:

https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/issues/147

There may be workarounds listed here:

https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar/issues/158
