### ISSUE TITLE
manual run/build: YAML 5.x dependency fails w/Python 3.11

### ISSUE THREAD

**Issue by grnassar** [Slashbunny/gog-galaxy-plugin-downloader#25]
Python 3.11 is apparently not liking the 5.x builds of PyYAML for some reason, as far as I can tell.  (More specifically one of its dependencies isn't handled well, but it's an upstream issue so no need to go into it here.)  I changed the requirements and built with 6.x, seemed to have no impact on functionality and works fine with 3.11 (and should work with any Python ver >2.7, according to the developer).

World's shortest PR incoming for this issue.

**Comment by Slashbunny** [comment]
Fixed by #26
